"""something changed

Revision ID: 43c5f57e73c1
Revises: 9f8aaf2b64bb
Create Date: 2023-11-29 13:41:50.664771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '43c5f57e73c1'
down_revision: Union[str, None] = '9f8aaf2b64bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usercountry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usercountry', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
