"""empty message

Revision ID: 9f8aaf2b64bb
Revises: 63204c36780d
Create Date: 2023-11-23 17:47:58.006024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9f8aaf2b64bb'
down_revision: Union[str, None] = '63204c36780d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('check', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'check')
    # ### end Alembic commands ###
